### ISSUE TITLE
for naccl，请大佬帮忙看看

### ISSUE THREAD

**Issue by zhinian1213** [zhinian1213/NewBlogRepository#1]
java.lang.NullPointerException
	at top.naccl.service.impl.BlogServiceImpl.setBlogViewsFromRedisToPageResult(BlogServiceImpl.java:152)
	at top.naccl.service.impl.BlogServiceImpl.getBlogInfoListByIsPublished(BlogServiceImpl.java:135)
	at top.naccl.service.impl.BlogServiceImpl$$FastClassBySpringCGLIB$$5890a2ac.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:687)
	at top.naccl.service.impl.BlogServiceImpl$$EnhancerBySpringCGLIB$$390fabe.getBlogInfoListByIsPublished(<generated>)
	at top.naccl.controller.BlogController.blogs(BlogController.java:47)
	at top.naccl.controller.BlogController$$FastClassBySpringCGLIB$$942814c2.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:88)
	at top.naccl.aspect.VisitLogAspect.logAround(VisitLogAspect.java:67)
	at sun.reflect.GeneratedMethodAccessor152.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:62)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
	at top.naccl.controller.BlogController$$EnhancerBySpringCGLIB$$3e11697.blogs(<generated>)
	at sun.reflect.GeneratedMethodAccessor184.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:879)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:126)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:90)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:118)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:158)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at top.naccl.config.JwtFilter.doFilter(JwtFilter.java:35)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:92)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:92)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:77)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

**Comment by Naccl** [comment]
我简单复现了一下，大概原因是 MySQL 中 blog 的 id 和 Redis key=`blogViewsMap` 中 blog 的 id 对应不上，或者 Redis 根本没有这个`blogViewsMap`的 key，但是在程序启动时，会预先将 MySQL 中的数据同步到 Redis，大概率还是你手动修改过 MySQL 或者 Redis。
方便的话截个图，MySQL 中 blog 的 id 字段，和 Redis 中`blogViewsMap`的 key。

**Comment by zhinian1213** [comment]
拿redis的key报错了是为什么







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhinian1213/NewBlogRepository"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月27日(星期四) 下午4:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhinian1213/NewBlogRepository] for naccl，请大佬帮忙看看 (Issue #1)





 
我简单复现了一下，大概原因是 MySQL 中 blog 的 id 和 Redis key=blogViewsMap 中 blog 的 id 对应不上，或者 Redis 根本没有这个blogViewsMap的 key，但是在程序启动时，会预先将 MySQL 中的数据同步到 Redis，大概率还是你手动修改过 MySQL 或者 Redis。
 方便的话截个图，MySQL 中 blog 的 id 字段，和 Redis 中blogViewsMap的 key。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhinian1213** [comment]
之前有手动改了一条数据，那条数据后来也删除了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhinian1213/NewBlogRepository"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月27日(星期四) 下午4:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhinian1213/NewBlogRepository] for naccl，请大佬帮忙看看 (Issue #1)





 
我简单复现了一下，大概原因是 MySQL 中 blog 的 id 和 Redis key=blogViewsMap 中 blog 的 id 对应不上，或者 Redis 根本没有这个blogViewsMap的 key，但是在程序启动时，会预先将 MySQL 中的数据同步到 Redis，大概率还是你手动修改过 MySQL 或者 Redis。
 方便的话截个图，MySQL 中 blog 的 id 字段，和 Redis 中blogViewsMap的 key。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Naccl** [comment]
读 Redis 本身不会报错，但是在`BlogServiceImpl ` 152 行有个强转 int 的操作，把从 Redis 取出的 null 转 int 的时候报的空指针。
所以不要手动修改 MySQL 或者 Redis 就好了。
如果一定要改，又不确定为什么报错，就把 Redis 对应 DB 中的所有 key 删除，然后重启后端服务就好了，重启过程中会自动同步。

**Comment by zhinian1213** [comment]
我是把db清空了再重启，反复了几次也没用，刚才一次是有两条博客出问题一条是没出问题，过会再看看行不行，大佬太强了，叨唠您了，请你喝阔落




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhinian1213/NewBlogRepository"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月27日(星期四) 下午4:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhinian1213/NewBlogRepository] for naccl，请大佬帮忙看看 (Issue #1)





 
读 Redis 本身不会报错，但是在BlogServiceImpl  152 行有个强转 int 的操作，把从 Redis 取出的 null 转 int 的时候报的空指针。
 所以不要手动修改 MySQL 或者 Redis 就好了。
 如果一定要改，又不确定为什么报错，就把 Redis 对应 DB 中的所有 key 删除，然后重启后端服务就好了，重启过程中会自动同步。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Naccl** [comment]
客气了，开源项目收 star 就是最大的快乐了🤗

**Comment by zhinian1213** [comment]
您好 我想在问问执行syncVisitInfoToDatabase 方法失败是什么问题






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhinian1213/NewBlogRepository"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月27日(星期四) 下午5:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhinian1213/NewBlogRepository] for naccl，请大佬帮忙看看 (Issue #1)





 
客气了，开源项目收 star 就是最大的快乐了🤗
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Naccl** [comment]
没异常堆栈我也猜不了

**Comment by zhinian1213** [comment]
上封邮件难道图片显示不了


2022-01-29 11:38:29.570 ERROR 28141 --- [eduler_Worker-5] top.naccl.util.quartz.ScheduleJob&nbsp; &nbsp; &nbsp; &nbsp; : 任务执行失败，任务ID：2


java.util.concurrent.ExecutionException: java.lang.RuntimeException: 执行定时任务失败
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at top.naccl.util.quartz.ScheduleJob.executeInternal(ScheduleJob.java:43)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.lang.RuntimeException: 执行定时任务失败
	at top.naccl.util.quartz.ScheduleRunnable.run(ScheduleRunnable.java:39)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at top.naccl.util.quartz.ScheduleRunnable.run(ScheduleRunnable.java:36)
	... 5 common frames omitted
Caused by: java.lang.NullPointerException: null
	at top.naccl.task.VisitorSyncScheduleTask.lambda$syncVisitInfoToDatabase$2(VisitorSyncScheduleTask.java:84)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at top.naccl.task.VisitorSyncScheduleTask.syncVisitInfoToDatabase(VisitorSyncScheduleTask.java:83)
	... 10 common frames omitted

------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhinian1213/NewBlogRepository"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月29日(星期六) 中午1:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhinian1213/NewBlogRepository] for naccl，请大佬帮忙看看 (Issue #1)





 
没异常堆栈我也猜不了
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Naccl** [comment]
你在 MySQL 执行一下 
```sql
select ip_source from visitor where date(create_time)=date_sub(curdate(), interval 1 day)
```
能否得到结果？

**Comment by zhinian1213** [comment]
null. 没有结果




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhinian1213/NewBlogRepository"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月29日(星期六) 中午1:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhinian1213/NewBlogRepository] for naccl，请大佬帮忙看看 (Issue #1)





 
你在 MySQL 执行一下
 select ip_source from visitor where date(create_time)=date_sub(curdate(), interval 1 day)
 
能否得到结果？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Naccl** [comment]
`visitor` 表能否截个图，`ip` 和 `ip_source` 这两列，我想知道你是怎么做到的

**Comment by zhinian1213** [comment]
可以看得到图片吗





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhinian1213/NewBlogRepository"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月29日(星期六) 中午1:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhinian1213/NewBlogRepository] for naccl，请大佬帮忙看看 (Issue #1)





 
visitor 表能否截个图，ip 和 ip_source 这两列，我想知道你是怎么做到的
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Naccl** [comment]
不能，你到 issues 来上传吧

**Comment by zhinian1213** [comment]
https://cdn.jsdelivr.net/gh/zhinian1213/NewBlogRepository/bug/78eb62e8-aef0-481f-9502-e6d4a670b786.png


这样子吧！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhinian1213/NewBlogRepository"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月29日(星期六) 中午1:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhinian1213/NewBlogRepository] for naccl，请大佬帮忙看看 (Issue #1)





 
不能，你到 issues 来上传吧
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Naccl** [comment]
在 log 目录下看看对应日期的日志文件有没有 ERROR 级别的 `getCityInfo exception`，看起来是 `ip2region` 解析 ip 时出了问题。

**Comment by zhinian1213** [comment]
好像没有看到诶




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhinian1213/NewBlogRepository"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月29日(星期六) 中午1:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhinian1213/NewBlogRepository] for naccl，请大佬帮忙看看 (Issue #1)





 
在 log 目录下看看对应日期的日志文件有没有 ERROR 级别的 getCityInfo exception，看起来是 ip2region 解析 ip 时出了问题。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhinian1213** [comment]
我重新部署了一下，那个同步方法可以执行成功了，但是ip来源还是获取不到，ip_source都是空的


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhinian1213/NewBlogRepository"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月29日(星期六) 中午1:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhinian1213/NewBlogRepository] for naccl，请大佬帮忙看看 (Issue #1)





 
在 log 目录下看看对应日期的日志文件有没有 ERROR 级别的 getCityInfo exception，看起来是 ip2region 解析 ip 时出了问题。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Naccl** [comment]
太怪了，[IpAddressUtils#getCityInfo](https://github.com/Naccl/NBlog/blob/8ba8c8deafeb4da962fcde74756335d6211cd9de/blog-api/src/main/java/top/naccl/util/IpAddressUtils.java?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L95) 这个方法，正常会返回 非 null 的 String，要么肯定会输出 ERROR 日志。

因为我用的 `memorySearch` 的调用方式，在程序启动时就加载 `ip2region` 的方法供反射调用，有没有检查程序启动时的日志是否存在 ERROR ？

尝试在 [IpAddressUtils 83行](https://github.com/Naccl/NBlog/blob/8ba8c8deafeb4da962fcde74756335d6211cd9de/blog-api/src/main/java/top/naccl/util/IpAddressUtils.java?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L83) 后加个日志打印
```java
method = searcher.getClass().getMethod("memorySearch", String.class);
log.debug("method : {}", method.getDeclaringClass());
```

[102行](https://github.com/Naccl/NBlog/blob/8ba8c8deafeb4da962fcde74756335d6211cd9de/blog-api/src/main/java/top/naccl/util/IpAddressUtils.java?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L102)后加日志
```java
String ipInfo = dataBlock.getRegion();
log.debug("ipInfo: {}", ipInfo);
```

然后看看程序启动时是否有 ERROR 级别的 `initIp2regionResource exception`，新访客访问时，`ipInfo` 的显示结果是如何。

**Comment by zhinian1213** [comment]
好奇怪啊，我加上了您说的那两个打印日志的，重新部署后那个就能拿到ip_resource,但是执行了那两个同步方法，dashboard的地图没有关系，pvuv折线图在更新28号的。还是说这样要每日凌晨它自动执行才能更新，手动的没用


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhinian1213/NewBlogRepository"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月29日(星期六) 下午3:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhinian1213/NewBlogRepository] for naccl，请大佬帮忙看看 (Issue #1)





 
太怪了，IpAddressUtils#getCityInfo 这个方法，正常会返回 非 null 的 String，要么肯定会输出 ERROR 日志。
 
因为我用的 memorySearch 的调用方式，在程序启动时就加载 ip2region 的方法供反射调用，有没有检查程序启动时的日志是否存在 ERROR ？
 
尝试在 IpAddressUtils 83行 后加个日志打印
 method = searcher.getClass().getMethod("memorySearch", String.class); log.debug("method : {}", method.getDeclaringClass());
 
102行后加日志
 String ipInfo = dataBlock.getRegion(); log.debug("ipInfo: {}", ipInfo);
 
然后看看程序启动时是否有 ERROR 级别的 initIp2regionResource exception，新访客访问时，ipInfo 的显示结果是如何。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Naccl** [comment]
显示截止前一天，今天29，就只会显示28的。

你想看变化的话，可以关闭定时任务，明天手动执行。

**Comment by zhinian1213** [comment]
好的好的，谢谢博主！！！又叨唠您一下午了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhinian1213/NewBlogRepository"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月29日(星期六) 下午3:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhinian1213/NewBlogRepository] for naccl，请大佬帮忙看看 (Issue #1)





 
显示截止前一天，今天29，就只会显示28的。
 
你想看变化的话，可以关闭定时任务，明天手动执行。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
